//var uniq = require('lodash/uniq');
var union = require('lodash/union');
var keys = require('lodash/keys');
var FileSaver = require('file-saver');

var styles = {
	'active' : {"fill": { type: 'solid', fgColor: '3D9970'}},
	'disabled': {"fill": {type: 'solid', fgColor: 'DDDDDD'}},
	'header': {"fill":{type:'solid', fgColor: '0074D9'}, "font":{color:"DDDDDD"} },
	'maroon-highlight': {"fill":{type:'solid', fgColor:'85144b'}, "font":{color:"FFFFFF"} },
	'grey-navy': {"fill":{type:'solid', fgColor:'DDDDDD'}, "font":{color:"001f3f"} },
	'grey-blue': {"fill":{type:'solid', fgColor:'DDDDDD'}, "font":{color:"001f3f"} }
};

var sheets = {};

function populate_sheet_from_array_of_arrays(sheet, array) {
	for (var i=0; i<array.length; i++){
		var row = array[i];
		for (var j=0; j<row.length; j++){
			var cell = row[j];
			cellProps = {
				'set': cell.value,
			};
			if (typeof(cell) !== 'object'){
				cellProps.set = cell;
			}
			else{
				if (cell.style){
					for (var prop in cell.style){
						if (cell.style.hasOwnProperty(prop)){
							cellProps[prop] = cell.style[prop];
						}
					}
				}
			}
			if (cellProps.set !== undefined && cellProps.set !== "" ){
				//the column/rows is switched from what you might think, j (column) goes first
				sheet.set(j + 1, i + 1, cellProps);
			}
			//we do not set undefined values
		}
	}
	return sheet;
}

function getDimensionsForNewSheet(array){
	var rows = array.length;
	var columns = 1;
	for (var i=0; i<array.length; i++){
		var row = array[i];
		var rowLength = row.length;
		if (rowLength > columns){columns = rowLength;}
	}
	return {'rows':rows, 'columns':columns};
}

function makeNewSheet(workbook, array, name){
	dimensions = getDimensionsForNewSheet(array);
	console.log(name + " " + JSON.stringify(dimensions));
	var newSheet = workbook.createSheet(name, dimensions.columns, dimensions.rows);
	setReasonableColumnWidths(dimensions, newSheet);
	sheets[name] = {sheet:newSheet, dimensions:dimensions};
	return newSheet;
}

function applyStylesToTheWholeSheet(sheetObj, styleObj){
	let cols = sheetObj.dimensions.columns;
	let rows = sheetObj.dimensions.columns;
	let sheet = sheetObj.sheet;
	for (var col=1; col<=cols; col++){
		for (var row=1; row<=rows; row++){
			if (styleObj.hasOwnProperty("font")){
				sheet.font(col, row, styleObj.font);
			}
			if (styleObj.hasOwnProperty("border")){
				sheet.border(col, row, styleObj.font);
			}
			if (styleObj.hasOwnProperty("fill")){
				sheet.fill(col, row, styleObj.font);
			}
		}
	}
}

function setReasonableColumnWidths(dimensions, worksheet){
	//by default, the column width will be only 8.43, or 64 pixels.
	//this is pretty miserable to work with
	//a more reasonable value is a width of 20
	//with the first column in a file always being shorter, at 15
	setColumnWidths(dimensions, worksheet, 20, 15);
}

function setColumnWidths (dimensions, worksheet, defaultWidth, firstWidth){
	for (var i=0; i<dimensions.columns; i++){
		if (i === 0 && firstWidth >= 0){
			worksheet.width(i+1, firstWidth);
		}
		else{
			worksheet.width(i+1, defaultWidth);
		}
	}
}

function setRowHeights (dimensions, worksheet, defaultHeight, firstHeight){
	for (var i=0; i<dimensions.rows; i++){
		if (i === 0 && firstHeight >= 0){
			worksheet.height(i+1, firstHeight);
		}
		else{
			worksheet.height(i+1, defaultHeight);
		}
	}
}

function setBorder(sheet, style, startLocation, direction){
	if (Array.isArray(startLocation)){
		//do some overload detection - if an array with two elements exists
		if (startLocation.length == 2){
			// then it is [x,y] and we convert to a property
			var x = startLocation[0];
			var y = startLocation[1];
			startLocation = {column:y, row:x};
		}
		else{
			throw ("startLocation dimensions are wrong");
		}
	}
	var column = startLocation.column;
	var row = startLocation.row;
	//direction gives us up or down, and length. For example, {long:5}
	if (typeof(direction) === 'number'){
		//we do some overloading, if direction is a number we just assume length
		direction = {'long':direction};
	}
	if (direction.hasOwnProperty('long')){
		var length = direction.long - 1;
		for (let i=column; i<length+column; i++){
			sheet.border(i,row,style);
		}
	}
	else {if (direction.hasOwnProperty('tall')){
		var height = direction.height - 1;
		for (let i=row; i<height+row; i++){
			sheet.border(row,i,style);
		}
	}}
}

function createSummarySheet(wb, report_suites, allAvailableReportSuites){
	var timeGeneratedAt = new Date();
	var timeGeneratedAtString = timeGeneratedAt.toLocaleString('en-US', {timeZoneName:'short'});
	var array = [ [{value:"Adobe Analytics Multi Reportsuite Configuration Report", "style":{font:{sz:18, bold:'true'}}}], [['']], ["Generated by Gene Jones's reportsuites.com"], ["Generated at " + timeGeneratedAtString] ];
	array.push(['']);
	array.push(['']);
	array.push(['']);
	if (report_suites.length === allAvailableReportSuites.length){
		array.push(["Reportsuites", "", "All available reportsuites for this account are listed."]);
	}
	else{
		array.push(["Reportsuites", "", "", "The portion of reportsuites for this account are listed."]);
	}
	
	array.push(['', {"value":"RSID"}, {"value":"Site Title"} ]);
	for (let i=0; i<report_suites.length; i++){
		array.push([[], {'value': report_suites[i].rsid, "style":{font:{iter:'true'}}}, {'value': report_suites[i].site_title, "style":{}}]);
	}
	if (report_suites.length !== allAvailableReportSuites.length){
		array.push(['']);
		array.push(['Non exported reportsuites', '', '', 'A list of reportsuites not included in this export.']);
		array.push(['', {"value":"RSID"}, {"value":"Site Title"} ]);
		for(let i=0; i<allAvailableReportSuites.length; i++){
			let isNotInSelectedSuites = true;
			for (let j=0; j<report_suites.length; j++){
				if (report_suites[j].rsid == allAvailableReportSuites[i].rsid){
					isNotInSelectedSuites = false;
					break;
				}
			}
			if (isNotInSelectedSuites){
				array.push([[], {'value': allAvailableReportSuites[i].rsid, "style":{font:{iter:'true'}}}, {'value': allAvailableReportSuites[i].site_title, "style":{}}]);
			}
		}
	}
	
	var sheetToPopulate = makeNewSheet(wb, array, "Summary");
	var ws = populate_sheet_from_array_of_arrays(sheetToPopulate, array);
	fileSummaryStyling(sheets["Summary"]);
	return ws;
}

function fileSummaryStyling(worksheetObj){
	applyStylesToTheWholeSheet(worksheetObj, styles['grey-navy']);
	let ws = worksheetObj.sheet;
	ws.width(1, 38); //set the first column to be wider
	ws.width(2, 30);
	ws.width(3, 30);
	ws.width(4, 48);
	ws.height(1,27); //the first row should also be taller
	ws.merge({col:1, row:1},{col:5, row:1}); //be a merged cell
	//and have a border
	setBorder(ws, {bottom:'thin'}, [1,1], 5);
}

var createOverviewOfSlot = function(report_suites, inputNVP, slotName, workbook){
	var outputArray = [];
	var firstRow = [[]];
	for (var i=0; i<report_suites.length; i++){
		firstRow.push({'value':report_suites[i].rsid, 'style':{font:{bold:'true'}, border:{bottom:'medium'}}});
	}
	outputArray.push(firstRow);
	var allKeys = []; //create a global list of keys for comparision
	for (let i=0; i<report_suites.length; i++){
		allKeys = union(allKeys, (keys(inputNVP[report_suites[i].rsid])) );
		console.log(allKeys);
	}
	for (let i=0; i<allKeys.length; i++){
		var key = allKeys[i];
		var row = [key];
		for (var j=0; j<report_suites.length; j++) {
			if (key in inputNVP[report_suites[j].rsid]) {
				var varOfInterest = inputNVP[report_suites[j].rsid][key];
				var obj = {"value":varOfInterest.name};
				if (varOfInterest.enabled || (slotName==="events" && varOfInterest.type!="disabled")){
					obj.style = styles.active;
				}
				else{
					obj.style = styles.disabled;
				}
				row.push(obj);
			}
			else{
				row.push('');
			}
		}
		outputArray.push(row);
	}
	var sheetToPopulate1 = makeNewSheet(workbook, outputArray, slotName);
	var ws2 = populate_sheet_from_array_of_arrays(sheetToPopulate1, outputArray);
};

var generateSummaryForReportSuite = function(report_suite, evars, props, events, workbook){
	var array = [];
	var columns = ["id", "name", "description", "type", "enabled", "expiration_type", "expiration_custom_days", "allocation_type", "default_metric", "participation", "serialization", "polarity", "visibility"];
	array.push(columns);
	var allVariables = [props, evars, events];
	var slotNames = ["props", "evars", "events"];
	for (var i=0; i<allVariables.length; i++){
		var slotName = slotNames[i];
		var vars = allVariables[i][report_suite];
		var allKeys = keys(vars);
		for (var j=0; j<allKeys.length; j++){
			var key = allKeys[j];
			var row = [];
			var varOfInterest = vars[key];
			for (var k=0; k<columns.length; k++){
				var column = columns[k];
				var obj = {};
				if (column in varOfInterest){
					obj.value = varOfInterest[column];
				}
				else{
					obj.value = 'N/A';
				}
				if (varOfInterest.enabled || (slotName==="events" && varOfInterest.type!="disabled")){
					obj.style = styles.active;
				}
				else{
					obj.style = styles.disabled;
				}
				row.push(obj);
			}
			array.push(row);
		}
	}
	
	var s = makeNewSheet(workbook, array, report_suite);
	var ws1 = populate_sheet_from_array_of_arrays(s, array);
};

function mapToNameValuePairs(array, nameofVarSlot){
	var rsid_mapping = {};
	for (var i=0; i<array.length; i++){
		var reportSuiteInfo = array[i];
		var rsid = reportSuiteInfo.rsid;
		var vars = reportSuiteInfo[nameofVarSlot];
		var nvp = {};
		for (var j=0; j<vars.length; j++){
			var presentVariable = vars[j];
			nvp[presentVariable.id] = presentVariable;
		}
		rsid_mapping[rsid] = nvp;
	}

	return rsid_mapping;
}

function exportSiteCatToExcel(report_suites, allAvailableReportSuites, evarArray, propArray, eventArray, fileName, callback) {
	//var workbook = excelbuilder.createWorkbook();
	//wrokbook.fname = fileName;
	var workbook = excelbuilder.createWorkbook("./", fileName);
	console.log("creating a summary/export sheet");
	let summarySheet = createSummarySheet(workbook, report_suites, allAvailableReportSuites);
	
	let evars = mapToNameValuePairs(evarArray, 'evars');
	let props = mapToNameValuePairs(propArray, 'props');
	let events = mapToNameValuePairs(eventArray, 'events');
	
	console.log("creating tabs for evars, props, and events");
	createOverviewOfSlot(report_suites, evars, "evars", workbook);
	createOverviewOfSlot(report_suites, props, "props", workbook);
	createOverviewOfSlot(report_suites, events, "events", workbook);
	
	console.log("creating tabs for each report suite");
	for (var i=0; i<report_suites.length; i++){
		var rs = report_suites[i];
		generateSummaryForReportSuite(rs.rsid, evars, props, events, workbook);
	}
	
	totalSheetsCreated = 1 + 3 + report_suites.length;
	summarySheet.set(1, 6, "This spreadsheet has " + totalSheetsCreated + " sheets.");
	
	workbook.generate(function(err, JSZip){
		if (err) return callback(err);
		
		JSZip.generateAsync({type: "blob", mimeType: 'application/vnd.ms-excel;'}).then(function (blob) {
			window.analytics.fileSize = blob.size;
			callback(true);
			FileSaver.saveAs(blob, fileName);
		});
	});
}

module.exports.exportSiteCatToExcel = exportSiteCatToExcel;